mrc-ide/hipercow

R/configure.R, R/task.R, drivers/windows/R/driver.R, drivers/windows/tests/testthat/test-driver.R, man/hermod_driver.Rd, tests/testthat/helper-hermod.R, tests/testthat/test-interface.R
~Merge after #12, as it contains those commits~
Fairly small changes, allows handling of task results, which is trivial for windows of course
=> Allow fetching task results via the driver

R/configure.R, R/provision.R, R/util.R, R/windows.R, README.md, tests/testthat/setup.R, tests/testthat/test-configure.R, tests/testthat/test-util.R, tests/testthat/test-windows.R
Small PR which means that users can just install `hermod` and we'll grab the rest as we need them.
We need to (later, I think) work out how to flag when version numbers are incompatible, that might take some care.
If you want to see this in action:
```r
remove.packages(c("hermod", "hermod.windows", "conan2"))
```
then from somewhere on the network share:
```
> hermod::hermod_init(".")
✔ Initialised hermod at '.'
ℹ Next, call 'hermod_configure()'
> hermod::hermod_configure("windows")
ℹ Trying to install 'hermod.windows'
ℹ To prevent this, set options(hermod.no_install_missing = TRUE)
Installing package into ‘/home/rfitzjoh/lib/R/library’
(as ‘lib’ is unspecified)
also installing the dependency ‘conan2’
trying URL 'https://mrc-ide.r-universe.dev/src/contrib/conan2_1.9.90.tar.gz'
Content …
```
=> Automatically install packages when requested

R/configure.R, R/root.R, R/util.R, drivers/windows/tests/testthat/helper-config.R, drivers/windows/tests/testthat/test-config.R, man/hermod_init.Rd, tests/testthat/test-configure.R, tests/testthat/test-interface.R, tests/testthat/test-root.R, tests/testthat/test-util.R, tests/testthat/test-zzz-integration.R
Allows passing `driver = "windows"` to `hermod_init()` which reduces boilerplate on initialisation. Also made `hermod_configure` more chatty
=> Allow configuration at initialisation

R/environment.R, man/hipercow_environment.Rd, tests/testthat/test-environment.R, tests/testthat/test-interface.R
This PR lets the user declare what variables we can rely on to exist within their created environment. There's a special value `TRUE` here which just builds the env and works it out
=> Allow advertising of globals

R/environment.R, R/task.R, tests/testthat/test-task-expression.R
This PR allows using globals when running a task. Validation included, but optional (and off by default)
=> Use globals within a task

Makefile, R/configure.R, R/task.R, drivers/windows/R/batch.R, drivers/windows/R/bootstrap.R, drivers/windows/R/config.R, drivers/windows/R/provision.R, drivers/windows/R/util.R, drivers/windows/inst/templates/bootstrap.R, drivers/windows/inst/templates/task_run.bat, drivers/windows/tests/testthat/setup.R, drivers/windows/tests/testthat/test-bootstrap.R, drivers/windows/tests/testthat/test-config.R, drivers/windows/tests/testthat/test-driver.R, tests/testthat/test-configure.R, tests/testthat/test-interface.R
This is fairly nasty set of changes, despite their modest size:
1. allow preventing a driver from loading while running on the cluster (be7a136)
2. fix some bugs that made me realise that the above bug was happening (6ae953c)
3. add a workflow to allow us to install the development sources of hipercow for use on the cluster easily (035bee1, 7c7ae34)
The first one was caused by `task_status()` trying to load the windows driver on the task as it was running on windows! I've put logic in to prevent this and an assertion that will fail nice and early should it happen again. We set an environment variable in the bootstrap that will prevent driver load.
The second one was a few different small bugs:
* we don't create the job library before setting `.libPaths()` to use it (via `R_LIBS_USER`) …
=> Allow preventing driver load

R/windows.R, drivers/windows/R/mounts.R, drivers/windows/R/paths.R, drivers/windows/tests/testthat/helper-config.R, drivers/windows/tests/testthat/test-config.R, drivers/windows/tests/testthat/test-mounts.R, drivers/windows/tests/testthat/test-paths.R, drivers/windows/tests/testthat/test-web.R, man/windows_path.Rd, tests/testthat/test-windows.R
Fairly mechanical - this is now unused everywhere so just drop it.
=> Drop 'name' argument from windows_path

drivers/windows/R/mounts.R, drivers/windows/tests/testthat/test-mounts.R, drivers/windows/windows.Rproj
Fix issue where windows seems to have a network share with no drive letter - which is a degraded/disconnected drive. 
This gets detected erroneously as an alternative home mountpoint, but this PR removes the problem at the source, rather than code to cope with weird results from the wmic call.
=> Filter out disconnected net shares

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/R/web.R, drivers/windows/tests/testthat/test-web.R
This PR logs back in, with a small message, after being logged out
=> Log in again after expiry

DESCRIPTION, R/task.R, drivers/windows/DESCRIPTION, man/task_cancel.Rd, man/task_wait.Rd, tests/testthat/test-interface.R, tests/testthat/test-task.R
This generalises `task_wait` a little by allowing us to wait until a task is at least running.  This has two uses:
* I was keen to use this in a vignette to cancel a running task (rather than just one that is waiting)
* We will want this in rrq perhaps to want until tasks are running (and not until they terminate)
=> mrc-4912: Allow waiting on tasks until they start running

DESCRIPTION, R/bundle.R, R/task.R, drivers/windows/DESCRIPTION, tests/testthat/test-bundle.R, tests/testthat/test-task.R
Just a helper function that will point people in the right direction if they pass a bundle to a task function by accident
=> Consistent error messages for ids and bundle arguments

DESCRIPTION, R/task-create.R, R/util.R, drivers/windows/DESCRIPTION, man/task_create_expr.Rd, tests/testthat/test-task-expression.R, tests/testthat/test-util.R
This is going to be useful for implementing `rrq`/workers support, and possibly for some advanced users.  The idea is to allow multi-line expressions contained in `{}` so for example
```r
task_create_expr({
x <- 1
f(x)
})
```
which will run the entire expression, "returning" the last line (this is the behaviour of `local` already).  We actually supported this already, just not usefully because in this case we should exclude `x` from our list of local variables; that's the meat of this PR.
=> Allow multiline expressions

DESCRIPTION, README.md, drivers/windows/DESCRIPTION, drivers/windows/R/provision.R, drivers/windows/R/util.R, drivers/windows/tests/testthat/test-provision.R, drivers/windows/tests/testthat/test-util.R
Old PR, new fix.
```
library(hipercow)
hipercow_init(driver = "windows", r_version = "4.3.0")
id <- task_create_expr(Sys.sleep(10))
hipercow_provision()
```
that should be enough to play around with it.
=> Check no running tasks before running installation

DESCRIPTION, R/task-retry.R, R/task.R, drivers/windows/DESCRIPTION, tests/testthat/test-task-retry.R, tests/testthat/test-task.R, vignettes/hipercow.Rmd, vignettes_src/hipercow.Rmd
This PR renames the field in the task info that retry chain information is saved in, and removes the odd addition of a "zero length chain" retry that was saved only once _any_ retries had been made
=> mrc-4915: improve retry chain info

DESCRIPTION, R/root.R, R/util.R, drivers/windows/DESCRIPTION, tests/testthat/test-root.R, tests/testthat/test-util.R
This PR stops me accidentally finding the hipercow *package* root when writing tests, when what I am expecting to find is the root that we are writing tests against.
I've also dropped rprojroot because it's not buying us here, and just pulled in the same code as in orderly/orderly2 that has served well over the years
=> Avoid accidentally finding the package root

DESCRIPTION, R/resource.R, R/submit.R, R/util.R, drivers/windows/DESCRIPTION, drivers/windows/tests/testthat/test-web.R, tests/testthat/helper-hipercow.R, tests/testthat/test-resource.R, tests/testthat/test-util.R
This PR harmonises and tests errors thrown during resource validation, passing the call through for nicer tracebacks and trying to reflect the argument name back.  The main aim was to update calls to `expect_error()` to add strings that match the error.
Churny but I did manage to simplify some of the time handling, which R makes particularly painful.  This avoids a few roundtrips through strings, and is I think a little easier to reason about though there is quite a bit of fighting terrible classes still.
While doing this I was wondering where the use of "original" is but did not really see anything obvious. Do you remember?
=> mrc-4951: harmonise errors from resource checks

DESCRIPTION, R/configure.R, R/constants.R, R/example.R, R/hello.R, R/submit.R, R/windows.R, drivers/windows/DESCRIPTION, drivers/windows/R/check.R, drivers/windows/R/driver.R, drivers/windows/R/mounts.R, drivers/windows/tests/testthat/test-check.R, drivers/windows/tests/testthat/test-driver.R, man/hipercow_driver.Rd, man/hipercow_hello.Rd, man/windows_check.Rd, tests/testthat/helper-hipercow.R, tests/testthat/test-bundle.R, tests/testthat/test-hello.R, tests/testthat/test-windows.R
This PR organises sending the hello world job through the fast queue.   No bootstrap update required, but we need to ensure that the windows driver and hipercow packages are both installed for it to work.
* new driver function that runs preflight checks and returns resources; this will be pretty general really
* the windows preflight checks now also check that the path is suitable
* resources are now saved as rds into the task directory, we can start using that when doing retries I think
There's one failure on windows only - Wes could you investigate? I think that it might just be that we need to do:
```
if (is_windows()) {
paths<- windows_path(...)
}
```
in the tests or implementation but I am not really sure what is triggering this
=> Support for sending the hello job to fast queue

DESCRIPTION, NAMESPACE, R/parallel.R, R/resource.R, R/submit.R, R/util.R, drivers/windows/DESCRIPTION, drivers/windows/R/driver.R, drivers/windows/R/provision.R, drivers/windows/R/web.R, drivers/windows/tests/testthat/test-driver.R, drivers/windows/tests/testthat/test-provision.R, drivers/windows/tests/testthat/test-web-support.R, drivers/windows/tests/testthat/test-web.R, man/hipercow_resources.Rd, tests/testthat/test-parallel.R, tests/testthat/test-resource.R
Seems ok throughout with this change.
Also added a print method for `hipercow_resources` and `hipercow_parallel`; both very simple and using the same little utility function
=> Drop "original" from all computed resources

DESCRIPTION, R/bundle.R, R/environment.R, R/util.R, drivers/windows/DESCRIPTION, man/hipercow_bundle_create.Rd, man/hipercow_environment.Rd, tests/testthat/test-bundle.R, tests/testthat/test-environment.R
Getting ahead of the inevitable saving of an environment or bundle with a `/`, `\` or `:` in it, which will fail badly.
Also adding in the idea of an "empty" environment, which comes from part of the rrq PR that I've paused until I get more of the rrq refactor finished
=> Validate that bundle and environment names are safe

DESCRIPTION, R/task-create.R, R/task-show.R, drivers/windows/DESCRIPTION, tests/testthat/test-task-call.R
I noticed this when porting the approach over to rrq, hopefully nothing that the users will do too much, but it can be useful
=> mrc-5058: allow unexported functions with task_create_call

DESCRIPTION, R/root.R, drivers/windows/DESCRIPTION, tests/testthat/test-root.R
Fixes this:-
```
setwd("Q:/testcow")
> hipercow::hipercow_provision()
Error in if (file.exists(path_description)) { : 
argument is of length zero
```
=> Better error for non-initialised root

DESCRIPTION, R/task.R, drivers/windows/DESCRIPTION, tests/testthat/test-task.R
Seen while debugging with Charlie.  The failing codecov is unrelated to us, and is being worked on by the actions team (https://github.com/r-lib/actions/issues/834)
=> Fix error in error message

.github/workflows/test-coverage.yaml, DESCRIPTION, R/environment.R, drivers/windows/DESCRIPTION, man/hipercow_environment.Rd, tests/testthat/test-environment.R, vignettes/troubleshooting.Rmd
This PR adds a check for problematic code in sources used for the environment creation.  At the moment this is limited to `install.packages()` but we might want to grow this over time (and perhaps have warnings about use of `library()` for example).
=> Check for problematic code in environment

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/R/check.R, drivers/windows/R/util.R, drivers/windows/R/zzz.R, drivers/windows/tests/testthat/test-check.R, drivers/windows/tests/testthat/test-util.R
We've hit issues where this was not obvious; now we check at startup and print instructions if people are in danger.  We might want to relax this in future.
=> Check that driver and main package are compatible

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/R/bootstrap.R, drivers/windows/R/config.R, drivers/windows/R/provision.R, drivers/windows/R/util.R, drivers/windows/tests/testthat/helper-hipercow.R, drivers/windows/tests/testthat/test-bootstrap.R, drivers/windows/tests/testthat/test-config.R
Checks on configure and provision that the versions used are not too old; too old is older than r-oldrel, at which point packages are hard to install.  We don't check this on use because at that point things should continue to work reasonably well.
The provided message is fairly gory but hopefully clear enough, and points people in the right direction. It can't be silenced easily so hopefully people will upgrade
=> Check that versions are new enough

DESCRIPTION, R/rrq.R, drivers/windows/DESCRIPTION, tests/testthat/test-rrq.R
The `hipercow_rrq_workers_submit` function was doing some processing of its resources and envvars arguments before passing them to `task_create_bulk_call`. The latter applied the exact same processing to these arguments.
For the most part, the processing is idempotent and only seeks to validate the inputs, so this only had a limited impact. The only exception is the encryption of secret variables, which was done twice, leading to undesirable behaviour.
Somehow the second encryption was failing rather than just performing a second layer of encryption. I think our use of the encryption routines has an upper limit on the size of payloads, and the outcome of the first round is larger than that limit. Regardless, we shouldn't be calling the encryption code twice, even if it had worked we would …
=> Remove duplicated processing of arguments in rrq setup.

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/inst/templates/task_run.bat
The batch file to run tasks checks for the presence of a `status-success` file when exiting, and derives its exit code from that. This is done to report useful status on the HPC web portal.
Unfortunately the path it was looking for was incorrect, therefore the file never existed and all jobs are reported as failed. This fixes the path by removing a spurious `log\` component.
=> Fix the path to the status file in the batch file.

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/R/bootstrap.R
Tiny PR, for where I wanted to run 
```
hipercow.windows:::bootstrap_update_all(versions = "4.4.1")
```
but had to write:
```
hipercow.windows:::bootstrap_update_all(versions = as.numeric_version("4.4.1"))
```
=> Use as.numeric_version in bootstrap

DESCRIPTION, R/environment.R, R/task-eval.R, drivers/windows/DESCRIPTION, tests/testthat/test-environment.R
hipercow silently attaches packages and sources files from the configured environment. If something goes wrong in this process (eg. the file does not exist), it can be difficult for users to understand what is happening. None of their own code makes any mention of the files or packages in question, and they may have forgotten that they ever created the environment.
This prints a message when loading the environment, with the list of files and packages that will be loaded. This should provide enough hints for the user to make the connection between a hypothetical error and the environment.
=> Print environment contents when loading it.

DESCRIPTION, R/configuration.R, drivers/windows/DESCRIPTION, tests/testthat/test-configuration.R
Small one here, which bit us when diagnosing a problem for a cluster user a few weeks/months ago - see ticket for details.
=> Never fail when looking up windows username fails when fetching configuration

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/R/batch.R, drivers/windows/R/paths.R, drivers/windows/inst/templates/task_run.bat, drivers/windows/tests/testthat/test-batch.R, drivers/windows/tests/testthat/test-paths.R
At present, the R_LIBS_USER path embedded in the batch file is relative to the working directory in which R is spawned. This generally works fine.
However, if the user's task switches working directories and then spawns a new R interpreter, then the new session will not be able to resolve the R_LIBS_USER anymore and the user's provisioned library won't be found.
This was an issue when a user was running an orderly task, which switches working directories to a draft folder, and then uses the parallel package, which spawns new R processes. Note that this is only an issue when users create their own clusters and not when using the builtin hipercow parallel support, since the latter explicitly inherits the libPaths.
By making the path absolute it now works regardless of which working …
=> Use an absolute path for R_LIBS_USER and R_ENVIRON_USER.

DESCRIPTION, R/parallel.R, R/rrq.R, R/task-eval.R, drivers/windows/DESCRIPTION, man/hipercow_rrq_controller.Rd, tests/testthat/test-parallel.R, tests/testthat/test-rrq.R
The `use_rrq` option was broken: it is supposed to initialize an rrq controller in the task's process, but in order to do so it needs to find the queue ID. There was code to read a queue ID from the environment, but nowhere relevant was that environment variable set. In theory it could read it from disk, but the `HIPERCOW_NO_DRIVERS` option did not allow that.
The tests for that functionality were passing because they were manually setting `HIPERCOW_RRQ_QUEUE_ID`.
This now passes the queue ID as part of the `parallel` argument to the task, fixing the issue. Added a more comprehensive test, which actually starts the rrq tasks from a hipercow task.
=> Allow rrq tasks to be started from a hipercow task.

DESCRIPTION, R/configuration.R, R/rrq.R, R/util.R, drivers/windows/DESCRIPTION, tests/testthat/test-configuration.R, tests/testthat/test-rrq.R, tests/testthat/test-util.R, vignettes/details.Rmd
We previously setup the rrq offload directory once when creating the queue, storing the absolute path to it in the redis database. Using a single global value breaks down when that directory is mounted on multiple machines but at differing paths.
The most spectacular failure case happens when configuring the queue from a linux machine and using it to run on a Windows cluster. When this happens, the offload path looks something like
`/home/<user>/path/to/project/hipercow/rrq/offload`, which when used from a Windows machine obviously does not work.
This is solved by configuring each instance of an `rrq_controller` with its own path to the offload directory, relative to the hipercow root. This root is already automatically adjusted based on where we are running.
=> Configure the rrq offload directory each time a controller is created.

DESCRIPTION, drivers/windows/DESCRIPTION, drivers/windows/R/mounts.R, drivers/windows/tests/testthat/test-mounts.R
Convert from WMIC to the Powershell Get-SmbMapping - which makes things simpler.
Also in some of the mounts test, file.exits("//server-a/b") was very slow - added a skip for testing, since we only call this internally.
The failing CI is vignette timeout again and one (but not both!) of the MacOS builds fails to get R 4.4.2
=> Don't use WMIC

DESCRIPTION, R/parallel.R, R/task-eval.R, R/util.R, drivers/windows/DESCRIPTION, tests/testthat/test-parallel.R, tests/testthat/test-util.R, tests/testthat/test-zzz-integration.R
This PR changes how we analyse expressions, preventing the first case in the original ticket failing:
```
> id <- task_create_expr(
expr = parallel::clusterApply(NULL, 1:2, function(x) {print(x)}),
parallel = hipercow_parallel("parallel"),
resources = resources)
Error in `rlang::env_get_list()`:
! Can't find `x` in environment.
```
=> Ignore function args when analysing expressions

DESCRIPTION, R/task-create.R, drivers/windows/DESCRIPTION, vignettes/administration.Rmd
Points at both vignettes now that cover relevant bits on this.  The fix won't work well unless the package is installed from r-universe because otherwise vignettes are not included.
I had to remove the bit from administration.Rmd - it was not rendering correctly (https://mrc-ide.github.io/hipercow/articles/administration.html#stan) and causing a warning on the vignette build; changing to make it actually call `hipercow.windows` causes a cyclic dependency.
=> Better error messages for big objects

.github/workflows/check-hipercow.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, R/environment.R, R/rrq.R, drivers/windows/DESCRIPTION, vignettes/parallel.Rmd, vignettes/troubleshooting.Rmd
After we update the `rrq` environment we should send an environment refresh request to any active workers, otherwise people will be confused that their tasks don't use the new environment (this is noticed in the docs already in #140).
This does mean that if a user creates the rrq controller, creates the rrq env and then launches workers, the workers will load the environment twice but that's fine.
=> Refresh worker environment after update

.github/workflows/check-hipercow.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, drivers/windows/DESCRIPTION
~Should do the same thing as the previous fix, but should work? https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs~
That didn't work, but this somehow does. Failure is just codecov adding noise, per usual
=> Try fixing temp location

.github/workflows/check-hipercow.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, R/example.R, R/util.R, drivers/windows/DESCRIPTION, tests/testthat/test-example.R, tests/testthat/test-task.R, tests/testthat/test-util.R, vignettes/common.R
This is used in #140 and #156, unfortunately it's not a complete fix as I'm still seeing some failures
=> Another approach to better temporary directories

DESCRIPTION, LICENSE, R/example.R, R/provision.R, drivers/windows/DESCRIPTION, drivers/windows/LICENSE, drivers/windows/R/cluster.R, drivers/windows/R/driver.R, drivers/windows/R/provision.R, drivers/windows/R/resource.R, drivers/windows/R/web.R, drivers/windows/tests/testthat/test-resource.R, tests/testthat/test-example.R
This replaces the hard-coded properties of the windows cluster with a read to the API at 
https://mrcdata.dide.ic.ac.uk/hpc/api/v1/cluster_info/wpia-hn/hipercow.windows/
and the next PR will use 
https://mrcdata.dide.ic.ac.uk/hpc/api/v1/cluster_info/wpia-hn/hipercow.linux/
This should help re-use parts of hipercow.windows - and just seems a better thing to do anyway, so that changes in queue/node/template can be done with the API rather than the code
=> Read cluster info from API

DESCRIPTION, R/configure.R, drivers/dide/DESCRIPTION, drivers/dide/R/batch.R, drivers/dide/R/config.R, drivers/dide/R/resource.R, drivers/dide/inst/templates/task_run.bat, drivers/dide/inst/templates/task_run.sh, drivers/dide/tests/testthat/helper-config.R, drivers/dide/tests/testthat/test-batch.R, drivers/dide/tests/testthat/test-config.R, man/hipercow_configure.Rd
Small tweak in the end - adds a new configuration option which seems to do the trick
```
library(hipercow)
hipercow_configure("dide-windows", redis_url = "wpia-hn2b.hpc.dide.ic.ac.uk")
hipercow_configuration()
r <- hipercow_rrq_controller()
redux::parse_info(r$con$INFO())$redis_version
```
=> Allow changing redis url
